name = "PhantomRevealer_GizmoExtension"
uuid = "6e16d361-b24e-494a-93f3-71642dcc5b47"
authors = ["Wei-Shan Su <weishansu011017@gmail.com>"]
version = "0.1.2"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
PhantomRevealer = "5c2dedaf-db9e-41c2-b778-b9f601995017"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Interpolations = "0.15.1"
